# Site settings
title: Peter Storch
email: peter.storch@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Peter Storchs GitHub pages. Let's see what I will do with it.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://pstorch.github.io" # the base hostname & protocol for your site
twitter_username: storchp
github_username:  pstorch
highlighter: pygments

# Build settings
markdown: kramdown
